account/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('account.views',
    url(r'^accounts/$', 'account_page', name="account_page"),
    url(r'^accounts/login/$', 'login_page', name="login_page"),
    url(r'^accounts/logout/$', 'logout_page', name="logout_page"),
    url(r'^register/$', 'register_page', name="register_page"),
    (r'^register/success/$', TemplateView.as_view(template_name='registration/register_success.html')),
)

blog/urls.py
# from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import FormView
from blog.forms import BlogPostSaveForm
from blog.api import BlogPostResource
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
urlpatterns = patterns('blog.views',
    (r'^$', 'main_page'),
    url(r'^user/(\w+)/$', 'user_page', name="user_page"),
    url(r'^user/(\w+)/draft/$', 'draft_page', name="draft_page"),
    (r'^tag/([^\s]+)/$', 'tag_page'),
    # (r'^tag/$', tag_cloud_page),
    (r'^search/$', 'search_page'),
    url(r'^blogpost/(\d+)/$', 'blogpost_detail_page', name="blogpost_detail"),
    url(r'^draft/(\d+)/$', 'draft_detail_page', name="draft_detail"),
    # (r'^site_media/(?P<path>.*)$', 'django.views.static.server',
    #     { 'document_root':site_media }),
    # (r'^site_media/css/(?P<path>.*)$', 'django.views.static.server',
    #     { 'document_root':site_media + '/css/' }),
    # (r'^site_media/js/(?P<path>.*)$', 'django.views.static.server',
    #     { 'document_root':site_media + '/js/' }),
    # (r'^site_media/img/(?P<path>.*)$', 'django.views.static.server',
    #     { 'document_root':site_media + '/img/' }),
    url(r'^save/$', 'blogpost_save_page', name="blogpost_save"),
    url(r'^blogpost/edit/(\d+)/$', 'blogpost_save_page', name="blogpost_update"),
    url(r'^blogpost/delete/(\d+)/$', 'blogpost_delete', name="blogpost_delete"),
    # Friends
    (r'^following/(\w+)/$', 'friends_page'),
    (r'^friend/add/$', 'friend_add'),
    (r'^friend/remove/$', 'friend_remove'),
    (r'^ajax/tag/autocomplete/$', 'ajax_tag_autocomplete'),
    url(r'^$', FormView.as_view(
        template_name="blogpost_detail.html",
        form_class=BlogPostSaveForm)),
)

# urlpatterns = [
#     # ... the rest of your URLconf goes here ...
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG :
#     urlpatterns += patterns('',
#         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
#     )

hashky/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from blog.api import BlogPostResource
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
blogpost_resource = BlogPostResource()
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hashky.views.home', name='home'),
    # url(r'^hashky/', include('hashky.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^ratings/', include('ratings.urls')),
    (r'^api/', include(blogpost_resource.urls)),
    url(r'^', include('blog.urls', namespace="blog")),
    url(r'^wechat/',include('wechat.urls', namespace="wechat")),
    url(r'^', include('account.urls', namespace="account")),
)
# urlpatterns = [
#     # ... the rest of your URLconf goes here ...
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wechat/urls.py
from django.conf.urls import patterns, include, url

urlpatterns=patterns('wechat.views',
    url(r'^$','index'),
    # url(r'^product//$','wechat.views.product_list'),
    url(r'^product/(\d+)/$','product_detail'),
    url(r'^binding/$', 'bind_wechat'),
    url(r'^product/(\w+)/$', 'product_page'),
    url(r'^product/$', 'product_main_page')
)

blog/models.py
# coding: UTF-8
from django.contrib.auth.models import User
from django.db import models

# class Profile(models.Model):
#     user = models.OneToOneField(User)
#     avatar = models.ImageField()
#     name = models.CharField()
#     description = models.TextField()

class BlogPost(models.Model):
    LIVE_STATUS = 1
    DRAFT_STATUS = 2
    STATUS_CHOICES = (
        (LIVE_STATUS, 'Live'),
        (DRAFT_STATUS, 'Draft'),
    )
    title = models.CharField(max_length=150)
    body = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User)
    status = models.IntegerField(choices=STATUS_CHOICES, default=LIVE_STATUS)
    def __str__(self):
        return '%s, %s' % (self.user.username, self.title)

class Collection(models.Model):
    name = models.CharField(max_length=150, unique=True)
    desc = models.TextField()
    user = models.ForeignKey(User)
    def __str__(self):
        return '%s, %s' % (self.user.username, self.name)

class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)
    blogposts = models.ManyToManyField(BlogPost)
    collections = models.ManyToManyField(Collection)
    def __str__(self):
        return self.name

class Followingship(models.Model):
    following = models.ForeignKey(
        User, related_name='following_set'
        )
    followers = models.ForeignKey(
        User, related_name='followers_set')
    def __unicode__(self):
        return u'%s, %s' % (self.following.username,
            self.followers.username)
    class Meta:
        unique_together = (('followers', 'following'), )

wechat/models.py
# coding: UTF-8
from django.contrib.auth.models import User
from django.db import models

class WechatUser(models.Model):
    openid = models.CharField(max_length=150)
    user = models.OneToOneField(User)

class Product(models.Model):
    # BUY = '0'
    # SELL = '1'
    # DEAL = '2'
    # STATUS_CHOICES = (
    #     (BUY, 'buy'),
    #     (SELL, 'sell'),
    #     (DEAL, 'deal'),
    # )
    name = models.CharField(max_length=150)
    desc = models.TextField()
    price = models.IntegerField()
    timestamp = models.DateTimeField()
    user = models.ForeignKey(WechatUser)
    status = models.CharField(max_length=1)
    # status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=SELL)

class Photo(models.Model):
    product = models.ForeignKey(Product)
    picurl = models.URLField()
    mediaid = models.CharField(max_length=150)

class Location(models.Model):
    product = models.ForeignKey(Product)
    x = models.FloatField()
    y = models.FloatField()
    label = models.CharField(max_length=150)

wechat/views.py
# Create your views here.
# coding: utf-8
import hashlib
from datetime import datetime
import pdb, time, re
import xml.etree.ElementTree as ET
from django.views.decorators.csrf import csrf_exempt
from django.utils.encoding import smart_str, smart_unicode
from wechat.models import *

from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.context_processors import csrf
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from django.template import RequestContext
from django.utils import simplejson
from ratings.handlers import ratings, RatingHandler
from ratings.forms import StarVoteForm, SliderVoteForm
from ratings.models import Vote
from django.core.urlresolvers import reverse
from blog.models import *

ratings.register(Product, form_class=StarVoteForm)
#pdb.set_trace()
kwd = {
    'main_menu' : "M",
    'start' : "##",
    'restart' : 'R',
    'buy' : '0',
    'sell' : '1',
    'view' : '2',
    'delete' : '3',
    'reset' : '*',
}
note = {
    'main_menu' : "To start pls input: \
                   [%s]Start to search products or to publish a sale\
                   [%s]Restart a buy or sell event\
                   [%s]View your on sale"
                    % (kwd['start'], kwd['restart'], kwd['view']),
    'buy_sell' : "Input: [%s]Buy [%s]Sell [%s]Reset" % (kwd['buy'], kwd['sell'], kwd['reset']),
    'product' : "Input product name",
    'location' : "Send your location",
    'photo' : "Send product photo",
    'price' : "Send product price",
    'desc' : "Send product description",
    'search' : 'Matching product...',
}
query_set={}

# def get_access_token():
def checkSignature(request):
    signature=request.GET.get('signature',None)
    timestamp=request.GET.get('timestamp',None)
    nonce=request.GET.get('nonce',None)
    echostr=request.GET.get('echostr',None)
    token='ettian'

    tmplist=[token,timestamp,nonce]
    tmplist.sort()
    tmpstr="%s%s%s"%tuple(tmplist)
    tmpstr=hashlib.sha1(tmpstr).hexdigest()
    if tmpstr == signature:
        return echostr
    else:
        return None

def bind_wechat(request):
    if request.method == 'POST':
        if request.session.has_key('openid') and request.session['openid'] == request.GET.get('openid', None):
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    wechatuser, created = WechatUser.objects.get_or_create(openid=request.session['openid'], user=user)
                    if created:
                        # Redirect to a success page.
                        return HttpResponse('WeChat user is binded to Hashky successfully!')
                    else:
                        return HttpResponse('WeChat user is already binded to a Hashky user')
                else:
                    # Return a 'disabled account' error message
                    return HttpResponse('Disabled account!')
            else:
                # Return an 'invalid login' error message.
                return HttpResponse('Invalid login!')
        else:
            return HttpResponse('Bind exception: no openid in session! Please send the bind request again')
    else:
        signature=request.GET.get('signature', None)
        timestamp = request.GET.get('timestamp', None)
        openid = request.GET.get('openid', None)
        token = 'bindhashky'
        tmplist=[token,timestamp,openid]
        tmplist.sort()
        tmpstr="%s%s%s"%tuple(tmplist)
        tmpstr=hashlib.sha1(tmpstr).hexdigest()
        if tmpstr == signature:
            if time.time() - int(timestamp) <= 1800:
                # save openid to session
                # Thanks to http://abyssly.com/2013/09/20/wx_bind/
                if not request.session.get('openid', False):
                    # return HttpResponse('Openid is not presented')
                    request.session['openid'] = openid
                return render_to_response('registration/bind_wechat.html')
            else:
                return HttpResponse('Link expired, please send binding request again')
        else:
            return HttpResponse("Security warning, please check if your account is leaked, and send binding request from official site.")


@csrf_exempt
def index(request):
    if request.method=='GET':
        return HttpResponse(checkSignature(request))
    elif request.method=="POST":
        return HttpResponse(msg_response(request), content_type="application/xml")
    else:
        return None

def parse_raw_xml(root_elem):
    msg = {}
    if root_elem.tag == 'xml':
        for child in root_elem:
            msg[child.tag] = smart_str(child.text)
    return msg

def get_reply(msg, reply):
    text_tpl = '''
    <xml>
    <ToUserName><![CDATA[%s]]></ToUserName>
    <FromUserName><![CDATA[%s]]></FromUserName>
    <CreateTime>%s</CreateTime>
    <MsgType><![CDATA[%s]]></MsgType>
    <Content><![CDATA[%s]]></Content>
    </xml>'''
    reply_msg = text_tpl % (
        msg["FromUserName"],
        msg["ToUserName"],
        str(int(time.time())),
        'text',
        reply)
    return reply_msg

def get_reply_article(msg, reply):
    # reply search product result
    multimedia_tpl = '''
    <xml>
    <ToUserName><![CDATA[%s]]></ToUserName>
    <FromUserName><![CDATA[%s]]></FromUserName>
    <CreateTime>%s</CreateTime>
    <MsgType><![CDATA[%s]]></MsgType>
    <ArticleCount>%s</ArticleCount>
    <Articles>
    '''
    item_tpl = '''
    <item>
    <Title><![CDATA[%(article_title)s]]></Title> 
    <Description><![CDATA[%(desc)s]]></Description>
    <PicUrl><![CDATA[%(picurl)s]]></PicUrl>
    <Url><![CDATA[%(url)s]]></Url>
    </item>'''
    close_tpl = '''
    </Articles>
    </xml>
    '''
    tpl_list = [multimedia_tpl]
    # biz goes here...
    for i in reply:
        item_tpl = item_tpl % i
        tpl_list.append(item_tpl)
    tpl_list.append(close_tpl)
    news_tpl = '\n'.join(tpl_list)
    reply_msg = news_tpl % (
        msg["FromUserName"],
        msg["ToUserName"],
        str(int(time.time())),
        'news',
        len(reply),)
    return reply_msg

def msg_response(request):
    # get request and parse raw xml
    raw_str = smart_str(request.raw_post_data)
    msg = parse_raw_xml(ET.fromstring(raw_str))
    # get text msg
    if msg['MsgType'] == 'event' and msg['Event'] == 'subscribe':
        # check if openid is already binded to system
        bind_link = ''
        token = 'bindhashky'
        openid = msg['FromUserName']
        timestamp = msg['CreateTime']
        tmplist=[token,timestamp,openid]
        tmplist.sort()
        tmpstr="%s%s%s"%tuple(tmplist)
        signature=hashlib.sha1(tmpstr).hexdigest()
        try:
            wechatuser = WechatUser.objects.get(openid=openid)
            if wechatuser.user == None:
                bind_link = '<a href="http://www.hashky.com/wechat/binding/?openid=%s&timestamp=%s&signature=%s">Please bind with Hashky account<a/>'\
                % (msg['openid'], timestamp, signature)
            else:
                return get_reply(msg, 'Welcome back!')
        except:
            bind_link = '<a href="http://www.hashky.com/wechat/binding/?openid=%s&timestamp=%s&signature=%s">Please bind with Hashky account<a/>'\
            % (openid, timestamp, signature)
        # send bind openid with system user request
        welcome = '''
        Hi, welcome to subscribe Hashky! To get a better service, please bind your WeChat account with Hashky account.
        '''
        return get_reply(msg, welcome+bind_link)
    elif msg['MsgType'] == 'event' and msg['Event'] == 'unsubscribe':
        goodbye = "Please don't leave me..."
        return get_reply(msg, goodbye)
    else:
        if msg['MsgType']=='text':
            query = msg.get('Content', 'You input nothing').strip()
        if msg['MsgType']=='location':
            query_x=msg.get('Location_X', 'You location is unknown')
            query_y=msg.get('Location_Y', 'You location is unknown')
            query_label=msg.get('Label', 'You location is unknown')
            query=(query_x,query_y,query_label)
        if msg['MsgType']=='image':
            query_picurl = msg.get('PicUrl', "You didn't send a product photo")
            query_mediaid = msg.get('MediaId', "You didn't send a product photo")
            query=(query_picurl, query_mediaid)
        return query_photo(msg, query)

def query_action(msg, query):
    # if buy or sell
    global query_set
    user = msg['FromUserName']
    if query == kwd['buy'] or query == kwd['sell']:
        query_set[user] = {}
        query_set[user]['action'] = query
        reply = note['product']
    #     # query db should start here
    #     return 
    else:
        reply = note['buy_sell']
    print query_set
    return get_reply(msg, reply)

def query_product(msg,query):
    global query_set
    user = msg['FromUserName']
    if query_set.has_key(user) and query_set[user].has_key('action'):
        #if product
        if type(query) is str:
            query_set[user]['product']=query
            reply = note['desc']
        else:
            reply = note['product']
    else:
        return query_action(msg,query)
    print query_set
    return get_reply(msg,reply)

def query_desc(msg, query):
    global query_set
    user = msg['FromUserName']
    if query_set.has_key(user) and query_set[user].has_key('product'):
        if type(query) is str:
            query_set[user]['desc']=query
            reply = note['price']
        else:
            reply = note['desc']
    else:
        return query_product(msg,query)
    print query_set
    return get_reply(msg,reply)

def query_price(msg,query):
    global query_set
    user = msg['FromUserName']

wechat/templates/wechat/base.html
{% extends "base.html" %}
{% block external %}
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="stylesheet" href="{{ STATIC_URL }}wechat/css/bootstrap.min.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}wechat/css/product-page.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
  <script src="{{ STATIC_URL }}wechat/jquery.js"></script>
  <script src="{{ STATIC_URL }}wechat/js/bootstrap.js"></script>
  <script src="{{ STATIC_URL }}wechat/js/nav.js"></script>
{% endblock %}

{% block nav%}
  <!-- Add top fixed nav bar -->
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
          type="button">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Hashky</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <a href="/">Home</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-left">
            <li>
              <a href="/save/">New</a>
            </li>
            <li>
              <a href="/search/">Search</a>
            </li>
            <li>
              <a href="/user/{{ user.username }}/">{{ user.username }}'s post</a>
            </li>
            <li>
              <a href="/wechat/product/">DongXi</a>
            </li>
            <li>
              <form id="search" action="/search" method="get" class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="search">
                </div>
              </form>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                {{ user.username }} <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <a href="{% url 'account:account_page' %}">
                    <span class="glyphicon glyphicon-cog"></span> Settings</a>
                </li>
                <li>
                  <a href="{% url 'account:logout_page' %}">
                    <span class="glyphicon glyphicon-off"></span> Logout</a>
                </li>
              </ul>
            </li>
          </ul>
        {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li>
              {% if request.path not in "/register/success/" and request.path not in "/accounts/login/" %}
                <a href="{% url 'account:login_page' %}?next={{ request.path }}">login</a>
              {% else %}
                <a href="{% url 'account:login_page' %}">login</a>
              {% endif %}
            </li>
            <li>
              <a href="{% url 'account:register_page' %}">sign up</a>
            </li>
          </ul>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

wechat/templates/wechat/product_detail.html
{% extends "wechat/base.html" %}
{% block title %}{{ product.name }}{% endblock %}
{% block head %}{{ product.name }}{% endblock %}
{% block content %}
  {{ product.name|markdown|safe }}
  {{ product.desc|markdown|safe }}
  {{ product.price|markdown|safe }}
  {{ product.timestamp|markdown|safe }}
  {{ product.user.user|markdown|safe }}
  {% include "blog/ratings.html" %}
  {% if user.id == product.wechatuser_id%}
    {% include "blog/ratings_form.html" %}
  {% endif %}
{% endblock %}

wechat/templates/wechat/product_list.html
<script src="{{ STATIC_URL }}wechat/js/delete.js"></script>
{% if products %}
  <div class="post-bucket">
    {% for product in products %}
      <div class="span3">
        <div class="post-item">
          <h2 class="post-item-title">
          <a href="/wechat/product/{{ product.id }}" class="title">{{ product.name }}</a></h2>
          <div class="row">
            <div class="span9">
              {% if show_user %}
                Posted by:  
                <a href="/user/{{ product.user.username }}/" class="username">
                {{ product.user.username }}</a>
              {% endif %}
            </div>
            <div class="span9">
              {% if show_edit %}
              <!-- <a href="/save/?id={{ blogpost.id|urlencode }}" class="edit">[edit]</a> -->
                <div class="post-controls">
                  <a href="{% url 'blogpost_update' blogpost.id %}" class="post tool edit">[edit]</a>
                </div>
                <div class="post-controls">
                  <a id="{{blogpost.id}}" href="javascript:void(0)" class="post tool delete">[delete]</a>
                </div>
              {% endif %}
            </div>
          </div>
          {% if show_body %}
            {{ product.desc|safe|truncatewords_html:20 }}<a href="/wechat/product/{{ product.id }}">Read more...</a>
          {% endif%}
          <br />
          <!-- {% if show_tags %}
            {% if blogpost.tag_set.all %}
              <div class="post-tags">
                {% for tag in blogpost.tag_set.all %}
                  <div class="post-tag">
                    #<a class="post-tag" href="/tag/{{ tag.name|urlencode }}/">{{ tag.name }}</a>
                  </div>
                {% endfor %}
              </div>
            {% else %}
            {% endif %}
          {% endif %} -->
        <hr />
        </div>
      </div>
    {% endfor %}
  </div>
{% else %}
  <p>No product found.</p>
{% endif %}

wechat/templates/wechat/product_main_page.html
{% extends "wechat/base.html" %}
{% block title %}Explore more products{% endblock %}
{% block head %}Explore more products{% endblock %}
{% block subhead %}See what we recommend{% endblock %}
{% block content%}
  {% if user.username %}
      {% include "wechat/product_list.html" %}
    <div class="row-fluid">
      <div class="span12">
        Recommended content      
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <div id="tag-cloud">
          {% for tag in tags %}
            <a href="/tag/{{ tag.name }}" class="tag-cloud-{{ tag.weight }}">
              {{ tag.name }}</a>
          {% empty %}
            Currently no tag!
          {% endfor %}
        </div>
      </div>
    </div>
  {% else %}
  	<p>Welcome anonymnous user!
  	You need to <a href="{% url 'account:login_page' %}?next=/">login</a>
  	before you can store and share products.</p>
  {% endif %}
{% endblock %}
{% block rcontent %}
  <h2>Following people</h2>
  {% if following_people %}
    <ul class="friends">
      {% for people in following_people %}
        <li><a href="/user/{{ people.username }}/">{{ people.username }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No following people found.</p>
  {% endif %}
{% endblock %}

wechat/templates/wechat/product_page.html
{% extends "wechat/base.html" %}
{% block title %}{{ username }}{% endblock %}
{% block head %}Products for {{ username }}{% endblock %}
{% block page %}
<script type="text/javascript">
  $(document).ready(function(){
    $("body").data("username", "{{username}}");
  });
</script>
<script src="{{ STATIC_URL }}wechat/js/follow.js"></script>{% endblock %}
{% block content %}
  {% include "wechat/product_list.html" %}
{% endblock %}
{% block rcontent %}
  {% ifequal user.username username %}
    <a href="/following/{{ username }}/">people you are following...</a>
    <a href="/tag-following/{{ username }}/">tags you are following...</a>
  {% else %}
    {% if is_following %}
      <a class="btn unfollow" href="javascript:void(0)">Unfollow</a>
    {% else %}
      <!-- <a class="btn icon follow" href="/friend/add/?username={{ username }}">Follow</a> -->
      <a class="btn btn-success follow" href="javascript:void(0)">Follow</a>
    {% endif %}
  {% endifequal %}
{% endblock %}