account/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('account.views',
    url(r'^accounts/$', 'account_page', name="account_page"),
    url(r'^accounts/login/$', 'login_page', name="login_page"),
    url(r'^accounts/logout/$', 'logout_page', name="logout_page"),
    url(r'^register/$', 'register_page', name="register_page"),
    (r'^register/success/$', TemplateView.as_view(template_name='registration/register_success.html')),
)

blog/urls.py
# from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import FormView
from blog.forms import BlogPostSaveForm
from blog.api import BlogPostResource
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
urlpatterns = patterns('blog.views',
    (r'^$', 'main_page'),
    url(r'^user/(\w+)/$', 'user_page', name="user_page"),
    url(r'^user/(\w+)/draft/$', 'draft_page', name="draft_page"),
    (r'^tag/([^\s]+)/$', 'tag_page'),
    # (r'^tag/$', tag_cloud_page),
    (r'^search/$', 'search_page'),
    url(r'^blogpost/(\d+)/$', 'blogpost_detail_page', name="blogpost_detail"),
    url(r'^draft/(\d+)/$', 'draft_detail_page', name="draft_detail"),
    # (r'^site_media/(?P<path>.*)$', 'django.views.static.server',
    #     { 'document_root':site_media }),
    # (r'^site_media/css/(?P<path>.*)$', 'django.views.static.server',
    #     { 'document_root':site_media + '/css/' }),
    # (r'^site_media/js/(?P<path>.*)$', 'django.views.static.server',
    #     { 'document_root':site_media + '/js/' }),
    # (r'^site_media/img/(?P<path>.*)$', 'django.views.static.server',
    #     { 'document_root':site_media + '/img/' }),
    url(r'^save/$', 'blogpost_save_page', name="blogpost_save"),
    url(r'^blogpost/edit/(\d+)/$', 'blogpost_save_page', name="blogpost_update"),
    url(r'^blogpost/delete/(\d+)/$', 'blogpost_delete', name="blogpost_delete"),
    # Friends
    (r'^following/(\w+)/$', 'friends_page'),
    (r'^friend/add/$', 'friend_add'),
    (r'^friend/remove/$', 'friend_remove'),
    (r'^ajax/tag/autocomplete/$', 'ajax_tag_autocomplete'),
    url(r'^$', FormView.as_view(
        template_name="blogpost_detail.html",
        form_class=BlogPostSaveForm)),
)

# urlpatterns = [
#     # ... the rest of your URLconf goes here ...
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG :
#     urlpatterns += patterns('',
#         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
#     )

hashky/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from blog.api import BlogPostResource
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
blogpost_resource = BlogPostResource()
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hashky.views.home', name='home'),
    # url(r'^hashky/', include('hashky.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^ratings/', include('ratings.urls')),
    (r'^api/', include(blogpost_resource.urls)),
    url(r'^', include('blog.urls', namespace="blog")),
    url(r'^wechat/',include('wechat.urls', namespace="wechat")),
    url(r'^', include('account.urls', namespace="account")),
)
# urlpatterns = [
#     # ... the rest of your URLconf goes here ...
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# coding: UTF-8
from django.contrib.auth.models import User
from django.db import models

# class Profile(models.Model):
#     user = models.OneToOneField(User)
#     avatar = models.ImageField()
#     name = models.CharField()
#     description = models.TextField()

class BlogPost(models.Model):
    LIVE_STATUS = 1
    DRAFT_STATUS = 2
    STATUS_CHOICES = (
        (LIVE_STATUS, 'Live'),
        (DRAFT_STATUS, 'Draft'),
    )
    title = models.CharField(max_length=150)
    body = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User)
    status = models.IntegerField(choices=STATUS_CHOICES, default=LIVE_STATUS)
    def __str__(self):
        return '%s, %s' % (self.user.username, self.title)

class Collection(models.Model):
    name = models.CharField(max_length=150, unique=True)
    desc = models.TextField()
    user = models.ForeignKey(User)
    def __str__(self):
        return '%s, %s' % (self.user.username, self.name)

class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)
    blogposts = models.ManyToManyField(BlogPost)
    collections = models.ManyToManyField(Collection)
    def __str__(self):
        return self.name

class Followingship(models.Model):
    following = models.ForeignKey(
        User, related_name='following_set'
        )
    followers = models.ForeignKey(
        User, related_name='followers_set')
    def __unicode__(self):
        return u'%s, %s' % (self.following.username,
            self.followers.username)
    class Meta:
        unique_together = (('followers', 'following'), )

blog/forms.py
from django import forms
from pagedown.widgets import PagedownWidget

class BlogPostSaveForm(forms.Form):
    title = forms.CharField(
        # label = 'Title',
        widget = forms.TextInput(attrs={'size': 128}))
    body = forms.CharField(
        # label='Post', 
        # widget=forms.Textarea())
        widget=PagedownWidget())
    tags = forms.CharField(
        # label='Tags',
        required = True,
        widget = forms.TextInput(attrs={'rows': 3}))

class SearchForm(forms.Form):
    query = forms.CharField(
        label=u'Search for',
        widget=forms.TextInput(attrs={'size':32})
        )

blog/views.py
import time, datetime
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.context_processors import csrf
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.models import User
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.utils import simplejson
from django.core.urlresolvers import reverse
from blog.forms import *
from blog.models import *
from ratings.handlers import ratings, RatingHandler
from ratings.forms import StarVoteForm, SliderVoteForm
from ratings.models import Vote
import pdb
ratings.register(BlogPost, form_class=StarVoteForm)
pdb.set_trace()
##def blog(request):
##    posts = BlogPost.objects.all()
##    return render_to_response('archive.html', locals())

# def main_page(request):
#     return render_to_response('main_page.html', RequestContext(request))

def user_page(request, username):
    user = get_object_or_404(User, username=username)
    # blogposts = user.blogpost_set.order_by('-id')
    blogposts = user.blogpost_set.filter(status=BlogPost.LIVE_STATUS).order_by('-id')
    if request.user.is_authenticated():
        is_following = Followingship.objects.filter(
            following=request.user,
            followers=user)
    else:
        is_following = False
    variables = RequestContext(request, {
        'username':username,
        'blogposts':blogposts,
        'show_tags': True,
        'show_body': True,
        'show_edit': username==request.user.username,
        'is_following': is_following,
        })
    return render_to_response('blog/user_page.html', variables)

def draft_page(request, username):
    user = get_object_or_404(User, username=username)
    # drafts = user.blogpost_set.order_by('-id')
    if request.user == user:
        drafts = user.blogpost_set.filter(status=BlogPost.DRAFT_STATUS).order_by('-id')
    else:
        raise Http403
    variables = RequestContext(request, {
        'username':username,
        'drafts':drafts,
        'show_tags': True,
        'show_body': True,
        'show_edit': username==request.user.username,
        })
    return render_to_response('blog/draft_page.html', variables)

def blogpost_detail_page(request, blogpost_id):
    if request.method == 'GET':
        blogpost = get_object_or_404(BlogPost, pk=blogpost_id)
        if blogpost:
            # cannot use _set query, because user and blogpost is not manytomany relationship
            # username = blogpost.user_set.all().values("username")[0]["username"]
            username = blogpost.user.username
        variables = RequestContext(request,{
            'blogpost': blogpost,
            # rename template variable to reuse rating and comment apps
            'object': blogpost,
            'show_tags': True,
            'show_body': True,
            'show_edit': username==request.user.username
            })
        return render_to_response('blog/blogpost_detail.html', variables)
    # directly publish from draft page via AJAX
    elif request.method == 'POST':
        if blogpost_id:
            blogpost, created = BlogPost.objects.get_or_create(user=request.user, pk=blogpost_id)
        blogpost.title = request.POST['title']
        blogpost.body = request.POST['body']
        # blogpost.time = datetime.datetime.now()
        tag_names = request.POST.getlist('tags[]')
        blogpost.status = BlogPost.LIVE_STATUS
        for tag_name in tag_names:
            tag, dummy = Tag.objects.get_or_create(name=tag_name)
            blogpost.tag_set.add(tag)
        blogpost.save()
        # return HttpResponseRedirect('/user/%s/' % request.user.username)
        # return HttpResponseRedirect(reverse('blogpost_detail_page', args=[blogpost_id]))
        return HttpResponseRedirect('/blogpost/%s/' % blogpost_id)

def draft_detail_page(request, blogpost_id):
    draft = get_object_or_404(BlogPost, pk=blogpost_id, status=BlogPost.DRAFT_STATUS)
    if request.user.id == draft.user_id:
        if request.method == 'GET':
            variables = RequestContext(request,{
                'draft': draft,
                'show_body': True,
                'show_tags': True,
                })
            return render_to_response('blog/draft_detail.html', variables)
    else:
        raise Http403

def _blogpost_save(request, form, status, id=None):
    blogpost, created = BlogPost.objects.get_or_create(user=request.user, pk=id)
    blogpost.body = form.cleaned_data['body']
    blogpost.title = form.cleaned_data['title']
    # blogpost.time = datetime.datetime.now()
    if not created:
        blogpost.tag_set.clear()
    tag_names = form.cleaned_data['tags'].split(',')
    blogpost.status = status
    for tag_name in tag_names:
        tag, dummy = Tag.objects.get_or_create(name=tag_name)
        blogpost.tag_set.add(tag)
    blogpost.save()
    return blogpost
# title = request.POST['title']
#         body = request.POST['title']
#         tags = request.POST['hidden-tags']
@login_required
def blogpost_save_page(request, id=None):
    if request.is_ajax():
        results={'success': True}
        json = simplejson.dumps(results)
        return HttpResponse(json, mimetype='application/json')
    if request.method == 'POST':
        tmp_req = request.POST.copy()
        tmp_req['tags'] = request.POST['hidden-tags']
        form = BlogPostSaveForm(tmp_req)
        if "submit_live" in request.POST:
            if form.is_valid():
                blogpost = _blogpost_save(request, form, BlogPost.LIVE_STATUS, id)
                return HttpResponseRedirect(
                    # reverse('user_page', args=[request.user.username])
                    '/user/%s/' % request.user.username
                    # '/blogpost/%s/' % id
                )
        # handle draft
        if "submit_draft" in request.POST:
            if form.is_valid():
                blogpost = _blogpost_save(request, form, BlogPost.DRAFT_STATUS, id)
                return HttpResponseRedirect(
                    # reverse('draft_page', args=[request.user.username])
                    '/user/%s/draft/' % request.user.username
                    # '/blogpost/%s/' % id
                )
    elif request.method == 'GET' and id:
        try:
            blogpost = BlogPost.objects.get(
                pk=id,
                user=request.user
                )
            body = blogpost.body
            title = blogpost.title
            tags = ' '.join(
                tag.name for tag in blogpost.tag_set.all()
                )
        except BlogPost.DoesNotExist:
            # restrict user to edit their own blogpost, 
            # so if others trying to access others' blog, force redirect to their own page.
            # return HttpResponseRedirect(reverse('user_page', args=[request.user.username]))
            return HttpResponseRedirect('/user/%s/' % request.user.username)
        form = BlogPostSaveForm({
            'body': body,
            'title': title,
            'tags': tags
            })
    else:
        form = BlogPostSaveForm()
    variables = RequestContext(request, {
        'user': request.user,
        'form':form
        })
    return render_to_response('blog/blogpost_save.html', variables)

@login_required
def blogpost_delete(request, id=None):
    username = request.user.username
    blogpost = get_object_or_404(BlogPost, pk=id)
    blogpost.delete()
    results={'success': True}
    json = simplejson.dumps(results)
    # return HttpResponse()
    # return HttpResponse(json, mimetype='application/json')
    if request.is_ajax():
        return HttpResponse(json, mimetype='application/json')
    else:
        return HttpResponseRedirect('/user/%s/' % username)
    # return HttpResponseRedirect(reverse('user_page', args=(username,)))
    # return HttpResponseRedirect('/user/%s/' % username)

def tag_page(request, tag_name):
    tag = get_object_or_404(Tag, name=tag_name)
    blogposts = tag.blogposts.filter(status=BlogPost.LIVE_STATUS).order_by('-id')
    variables = RequestContext(request, {
        'blogposts':blogposts,
        'tag_name':tag_name,
        'show_tags':True,
        'show_user':True,
        'show_body':True,
        })
    return render_to_response('blog/tag_page.html', variables)

# def tag_cloud_page(request):
@login_required
def main_page(request):
    import recommendations as rec
    # recommended posts
    # get user data
    user = request.user
    blogpost = BlogPost.objects.latest('id')
    handler = ratings.get_handler(blogpost)
    # others = User.objects.filter().exclude(username=user)
    # for test all users
    users = User.objects.all()
    critics = {}
    for other in users:
        voted = handler.has_voted(blogpost,'main', other)
        if voted:
            scores = {}
            for vote in ratings.get_votes_by(other):
                scores[vote.content_object.title] = vote.score
                # print "%s -> %s" % (vote.content_object.title, vote.score)
            if scores != {}:
                critics[other] = scores
    print rec.getRecommendations(critics, user)
        
    # latest avtivities from following people
    following_people = [followingship.followers for followingship in user.following_set.all()]
    following_people_blogposts = BlogPost.objects.filter(
        user__in=following_people,
        status=BlogPost.LIVE_STATUS,
        ).order_by('-id')


    MAX_WEIGHT = 5
    tags = Tag.objects.order_by('name')
    # calculate tag, min and max counts.
    if len(tags) != 0:
        min_count = max_count = tags[0].blogposts.count()
        for tag in tags:
            tag.count = tag.blogposts.count()
            if tag.count < min_count:
                min_count = tag.count
            if max_count < tag.count:
                max_count = tag.count
        #calculate count range. Avoid dividing by zero.
        range = float(max_count - min_count)
        if range == 0.0:

blog/templates/blog/base.html
{% extends "base.html" %}
{% block external %}
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="stylesheet" href="{{ STATIC_URL }}blog/css/bootstrap.min.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}blog/css/blog.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
  <script src="{{ STATIC_URL }}blog/jquery.js"></script>
  <script src="{{ STATIC_URL }}blog/js/bootstrap.js"></script>
  <script src="{{ STATIC_URL }}blog/js/nav.js"></script>
{% endblock %}

{% block nav%}
  <!-- Add top fixed nav bar -->
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
          type="button">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Hashky</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <a href="/">Home</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-left">
            <li>
              <a href="/save/">New</a>
            </li>
            <li>
              <a href="/search/">Search</a>
            </li>
            <li>
              <a href="/user/{{ user.username }}/">{{ user.username }}'s post</a>
            </li>
            <li>
              <a href="/wechat/product/">DongXi</a>
            </li>
            <li>
              <form id="search" action="/search" method="get" class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="search">
                </div>
              </form>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                {{ user.username }} <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <a href="{% url 'account:account_page' %}">
                    <span class="glyphicon glyphicon-cog"></span> Settings</a>
                </li>
                <li>
                  <a href="{% url 'account:logout_page' %}">
                    <span class="glyphicon glyphicon-off"></span> Logout</a>
                </li>
              </ul>
            </li>
          </ul>
        {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li>
              {% if request.path not in "/register/success/" and request.path not in "/accounts/login/" %}
                <a href="{% url 'account:login_page' %}?next={{ request.path }}">login</a>
              {% else %}
                <a href="{% url 'account:login_page' %}">login</a>
              {% endif %}
            </li>
            <li>
              <a href="{% url 'account:register_page' %}">sign up</a>
            </li>
          </ul>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends "blog/base.html" %}
{% block title %}{{ blogpost.title }}{% endblock %}
{% block head %}{{ blogpost.title }}{% endblock %}
{% block content %}
  <div class="blog-post-meta">
    Created in {{ blogpost.create_time|timesince }} ago
  </div>
  {{ blogpost.body|markdown|safe }}
  <div class="blog-post-meta">
    Last modified in {{ blogpost.modify_time|timesince }} ago
  </div>
  {% if show_tags %}
    {% if blogpost.tag_set.all %}
      <div class="post-tags">
        {% for tag in blogpost.tag_set.all %}
          <div class="post-tag">
            #<a class="post-tag" href="/tag/{{ tag.name|urlencode }}/">{{ tag.name }}</a>
          </div>
        {% endfor %}
      </div>
    {% else %}
    {% endif %}
  {% endif %}
  {% if show_edit %}
    <ul class="list-inline opts">
      <li>
        <a href="{% url 'blog:blogpost_update' blogpost.id %}">
          <span class="glyphicon glyphicon-pencil"></span>
        </a>
      </li>
      <li>
        <form name="deleteForm" onsubmit="return confirm('Are you sure you want to delete this post?')" method="post" action="{% url 'blog:blogpost_delete' blogpost.id %}">
          {% csrf_token %}
          <a href="javascript:if(confirm('Are you sure you want to delete?')){deleteForm.submit();}">
            <span class="glyphicon glyphicon-trash"></span>
          </a>
        </form>
      </li>
    </ul>
  {% endif %}
  <div class="review">
    Review
    <div class="vote-summary">
      {% include "blog/ratings.html" %}
    </div>
    {% if user.id != blogpost.user_id%}
      {% include "blog/ratings_form.html" %}
    {% endif %}
  </div>
<!--   {% include "blog/comments/comments.html" %}
  {% include "blog/comments/comment_form.html" %} -->
{% endblock %}

blog/templates/blog/blogpost_save.html
{% extends "blog/base.html" %}
{% block title %}New shares{% endblock %}
{% block head %}Share new ideas{% endblock %}
{% block subhead %}{% endblock %}
{% block page %}
    {{ form.media }}
    <link rel="stylesheet" href="{{ STATIC_URL }}blog/css/jquery.ui.autocomplete.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}blog/css/new-post.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}tagmanager/tagmanager.css">
    <!-- <link rel="stylesheet" href="{{ STATIC_URL }}jQuery-Tags-Input/jquery.tagsinput.css"> -->
    <!--<script type="text/javascript" src="{{ STATIC_URL }}blog/js/jquery.ui.autocomplete.js"></script>-->
    <script type="text/javascript" src="{{ STATIC_URL }}tagmanager/tagmanager.js"></script>
    <!--<script type="text/javascript" src="{{ STATIC_URL }}tiny_mce/tiny_mce.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}jQuery-Tags-Input/jquery.tagsinput.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/tag_autocomplete.js"></script>-->
    <script type="text/javascript">
        // jQuery(".tm-input").tagsManager();
    // tinyMCE.init({
    //     mode: "textareas",
    //     theme: "advanced",
    //     theme_advanced_resizing : true
    // });
    // $(document).ready(function(){
    //     // $('#tags').tagsInput();
    //     $('.tm-input').tagsManager({
    //          // hiddenTagListId: 'hidden_tags'
    //     });
    //     // $('#id_tags').tagsManager();
    //     // });
    //     $('#btn').click(function(){
    //         $('#tags').val($(':hidden_tags').val());
    //     });
    // });
        $(function(){
            $('.tm-input').tagsManager({
                // hiddenTagListId: 'hidden_tags'
                // AjaxPush: 'blogpost/edit/(\d+)/',
                // AjaxPushAllTags: true
                // AjaxPushParameters: { 'authToken': 'foobar' }
            });
        });
        // $('button').click(function(){
        //     $('#tags').val($("[name='hidden-tags']").val());
        // });
        
    </script>
{% endblock %}
{% block content %}
<div class="shortcuts">
    <a href="/user/{{ user }}/" class="username">My posts</a>
    <a href="/user/{{ user }}/draft" class="username">My drafts</a>
</div>
<form class="forms-new-post" method="post" action=".">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
        {{ form.title.errors }}
        <!-- {{ form.title }} -->
        <input class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.html_name }}" type="text" autofocus="" required="" value="{{ form.title.value|default:'' }}" placeholder="Input title..." />
    </div>
    <div class="form-group">
        {{ form.body.errors }}
        {{ form.body }}
       <!--  <textarea class="wmd-input form-control" id="{{ form.body.id_for_label }}" name="{{ form.body.html_name }}" placeholder="Body" /> -->
    </div>
    <div class="form-group">
        {{ form.tags.errors }}
        <input name="{{ form.tags.html_name }}" id="{{ form.tags.id_for_label }}" type="text" placeholder="Input tags..." value="{{ form.tags.value|default:'' }}" class="tm-input form-control" />
    </div>
    <div class="form-group">
        <button name="submit_live" value="submit" type="submit" class="btn btn-success">
          <span class="glyphicon glyphicon-ok"></span> Submit</button>
        <button name="submit_draft" value="save as draft" type="submit" class="btn btn-warning">
          <span class="glyphicon glyphicon-lock"></span> Save as draft</button>
    </div>
    <!-- <input type="submit" value="save" /> -->
</form>
{% endblock %}

blog/templates/blog/draft_list.html
{% load markup %}
{% if drafts %}
  {% for draft in drafts %}
    <div class="blog-post">
      <h2 class="blog-post-title"><a href="/draft/{{ draft.id }}" class="title">{{ draft.title }}</a></h2>
        <div class="blog-post-meta">
          {{ draft.create_time }}
        </div>
        {% if show_body %}
          {{ draft.body|markdown|safe|truncatewords_html:300 }}
          {% ifnotequal blogpost.body|markdown|safe|truncatewords_html:30|length blogpost.body|markdown|safe|truncatewords_html:31|length %}
            <a href="/draft/{{ draft.id }}">Read more...</a>
          {% endifnotequal %}
        {% endif%}
        <br />
        {% if show_tags %}
          {% if draft.tag_set.all %}
            <div class="post-tags">
              {% for tag in draft.tag_set.all %}
                <div class="post-tag">
                  #<a class="post-tag" href="/tag/{{ tag.name|urlencode }}/">{{ tag.name }}</a>
                </div>
              {% endfor %}
            </div>
          {% else %}
          {% endif %}
        {% endif %}
      <hr />
    </div>
  {% endfor %}
{% else %}
  <p>No draft.</p>
{% endif %}

blog/templates/blog/main_page.html
{% extends "blog/base.html" %}
{% block title %}Explore more interests{% endblock %}
{% block head %}Explore more interests{% endblock %}
{% block subhead %}See what we recommend{% endblock %}
{% block content%}
  {% if user.username %}
      {% include "blog/blogpost_list.html" %}
    <div class="row-fluid">
      <div class="span12">
        Recommended content      
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <div id="tag-cloud">
          {% for tag in tags %}
            <a href="/tag/{{ tag.name }}" class="tag-cloud-{{ tag.weight }}">
              {{ tag.name }}</a>
          {% empty %}
            Currently no tag!
          {% endfor %}
        </div>
      </div>
    </div>
  {% else %}
  	<p>Welcome anonymnous user!
  	You need to <a href="{% url 'blog:login_page' %}?next=/">login</a>
  	before you can store and share blogs.</p>
  {% endif %}
{% endblock %}
{% block rcontent %}
  <h2>Following people</h2>
  {% if following_people %}
    <ul class="friends">
      {% for people in following_people %}
        <li><a href="/user/{{ people.username }}/">{{ people.username }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No following people found.</p>
  {% endif %}
{% endblock %}

blog/templates/blog/ratings_form.html
<link href="{{ STATIC_URL }}blog/css/jquery.rating.css" rel="stylesheet" type="text/css" />
<script src="{{ STATIC_URL }}js/jquery-ui/ui/jquery-ui.js" type="text/javascript"></script>
<script type="text/javascript" src="{{ STATIC_URL }}blog/js/jquery.MetaData.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}blog/js/jquery.rating.js"></script>
<script src="{{ STATIC_URL }}blog/js/ratings.js" type="text/javascript"></script>
{% load ratings_tags %}

{% get_rating_form for object as rating_form %}
<form action="{% url 'ratings_vote' %}" class="ratings" method="post">
  {% csrf_token %}
    <ul class="list-inline">
      <li>{{ rating_form }}</li>
      <li>
        {% if user.is_authenticated %}
          <!-- <button class="btn btn-default" type="submit" value="Vote">vote</button> -->
        {% else %}
          <a class="btn btn-default" href="{% url 'account:login_page' %}?next={{ request.path }}">vote</a>
        {% endif %}
        </li>
    <span class="success" style="display: none;">Vote submited!</span>
    <span class="error" style="display: none;">Login is required before rating.</span>
    </ul>
</form>